spring:
  config:
    activate:
      on-profile: secret

  application:
    name: koreait

  # JDBC가 MySql에 접속하기 위한 정보
  datasource:
    url: jdbc:mysql://localhost:3306/koreaitweb2
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration: # 우리 서버가 동록한 oauth 목록
          google:
            client-id: 544699115570-bb79uoha2r8elgv94b9hvdj7mou66v8e.apps.googleusercontent.com
            client-secret:
            scope:
              - profile
              - email
            # 구글이 사용자 인증을 마친 후 인증코드를 붙혀 돌려보낼 우리 서버 주소
            # 라이브러리에서 알아서 엔드포인트를 만들어 놨음.
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        # provider: 상대 oauth의 실제 엔드포인트 주소들
      provider:
        google:
          # 로그인/동의 팝업화면 주소.
          authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
          # 인증코드를 accessToken으로 교환하는주소
          token-uri: https://oauth2.googleapis.com/token
          # accessToken으로 사용자 프로필 조회하는 주소
          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          # 사용자 프로필 응답에서 pk로 쓸 필드명
          user-name-attribute: sub # 구글은 sub 고정

# jwt는 조작여부를 secret난수를 가지고 발급했던 당시의 값과 동일한지 검사
jwt:
  secret: 4/DQIKsIrwNTgX0aqxrKjp/NfdJ5dr9qXZyXmw9g7gce9dqm20eoJ4rOfcDZ+YTC6FRllx/cjefOvjTJwWH92A==
  access-expire-millis: 900000 # 15분  15 * 60 * 1000