spring:
  config:
    activate:
      on-profile: secret

  application:
    name: koreait

  # JDBC가 MySql에 접속하기 위한 정보
  datasource:
    url: jdbc:mysql://localhost:3306/koreait_web2
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

# jwt는 조작여부를 secret난수를 가지고 발급했던 당시의 값과 동일한지 검사
jwt:
  secret: 4/DQIKsIrwNTgX0aqxrKjp/NfdJ5dr9qXZyXmw9g7gce9dqm20eoJ4rOfcDZ+YTC6FRllx/cjefOvjTJwWH92A==
  access-expire-millis: 900000 # 15분  15 * 60 * 1000